{
    'name': 'Veterinary Clinic',
    'version': '17.0.1.0.0',
    'summary': 'A management system for veterinary clinics',
    'author': '<Ángel Larralde>, Zzircon',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'hr',
    ],
    'data': [
        "wizards/veterinary_appointment_states_update_wizard.xml",
        "wizards/veterinary_surgery_states_update_wizard.xml",
        "wizards/veterinary_appointment_create_wizard.xml",
        'data/veterinary_species.xml',
        'data/ir_cron.xml',
        'data/ir_sequence_data.xml',
        'security/res_groups.xml',
        'security/ir_rule.xml',
        'security/ir.model.access.csv',
        'views/veterinary_pet.xml',
        'views/veterinary_appointment.xml',
        'views/veterinary_species.xml',
        'views/veterinary_surgery.xml',
        'views/veterinary_allergy.xml',
        'views/veterinary_insurance.xml',
        'views/veterinary_appointment_line.xml',
        "views/veterinary_adoption.xml",
        "reports/veterinary_appointment_report.xml",
        "reports/veterinary_appointment_list_report.xml",
        "reports/veterinary_insurance_report.xml",
        "reports/veterinary_surgery_report.xml",
    ],
    'application': False,
    'installable': True,
}