from . import product_template
from . import res_partner
from . import veterinary_adoption
from . import veterinary_adoption_stage
from . import veterinary_allergy
from . import veterinary_appointment
from . import veterinary_appointment_line
from . import veterinary_appointment_tag
from . import veterinary_insurance
from . import veterinary_pet
from . import veterinary_species
from . import veterinary_surgery
from . import veterinary_surgery_line
from . import veterinary_veterinarian
