{
    'name': 'Veterinary Clinic',
    'version': '17.0.1.0.0',
    'description': 'A management system for a veterinary clinic',
    'summary': '',
    'author': '<Aleix Leon>, PlanetaTIC',
    'website': '',
    'license': 'LGPL-3',
    'category': '',
    'depends': [
        'hr',
    ],
    # load data in order
    'data': [
        'data/veterinary_species_data.xml',
        'data/ir_cron.xml',
        'data/ir_sequence.xml',
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'wizard/veterinary_appointment_edit_state.xml',
        'wizard/veterinary_appointment_mass_generation.xml',
        'wizard/veterinary_surgery_edit_state.xml',
        'views/view_product_template.xml',
        'views/res_partner_views.xml',
        'views/veterinary_adoption.xml',
        'views/veterinary_allergy.xml',
        'views/veterinary_appointment.xml',
        'views/veterinary_appointment_line.xml',
        'views/veterinary_insurance.xml',
        'views/veterinary_pet.xml',
        'views/veterinary_species.xml',
        'views/veterinary_surgery.xml',
        'views/veterinary_veterinarian.xml',
        'views/veterinary_menus.xml',
        'report/veterinary_appointment_report.xml',
        'report/veterinary_insurance_report.xml',
        'report/veterinary_surgery_report.xml',
    ],
    'auto_install': False,
    'application': False,
    'installable': True,
}
